### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by nickjuntilla** [MetaMask/eth-json-rpc-middleware#11]
Could you please provide an example of using this with https://github.com/MetaMask/web3-provider-engine ?

**Comment by rekmarks** [comment]
Hello, I apologize for the delayed response. Unfortunately, we are no longer committed to maintaining or supporting `web3-provider-engine`. This module is designed to work with [`json-rpc-engine`](https://npmjs.com/package/json-rpc-engine) above all. I recommend moving to `json-rpc-engine` and composing an appropriate middleware stack. You can see how we do so in the MetaMask extension [here](https://github.com/MetaMask/metamask-extension/blob/54e9c53b27823452b359e07030c41ffaf8c73974/app/scripts/metamask-controller.js/#L1930-L2006) and [here](https://github.com/MetaMask/metamask-extension/blob/54e9c53b27823452b359e07030c41ffaf8c73974/app/scripts/controllers/network/createInfuraClient.js).
