### ISSUE TITLE
Is it updated on npm?

### ISSUE THREAD

**Issue by logvik** [MetaMask/eth-json-rpc-middleware#18]
We did merge https://github.com/MetaMask/eth-json-rpc-middleware/pull/17, but the package on npm is 4.3.0 that has only `decrypt_message` feature https://www.npmjs.com/package/eth-json-rpc-middleware (Updated on 5 October), although merge for `ecryption_public_key` has been on 8 November.

**Comment by logvik** [comment]
We need it for MetaMask/metamask-extension#1190

**Comment by lazaridiscom** [comment]
You can for now just add the github repo as a dependency to package.json.

(and of course the usual `yarn link` method)

**Comment by danfinlay** [comment]
Published as `eth-json-rpc-middleware@4.4.0`
