### ISSUE TITLE
Custom errors overwritten

### ISSUE THREAD

**Issue by StrathCole** [MetaMask/eth-json-rpc-middleware#338]
The code in the fetch middleware forcefully overwrites any received error with a meaningless "internal JSON-RPC error".
Is there a valid reason to do that? If the JSON-RPC returns a valid error object with a correct code, message (and eventually data), why is that not used?

```
function parseResponse(fetchRes: Response, body: Record<string, Block>): Block {
  // check for error code
  if (fetchRes.status !== 200) {
    throw rpcErrors.internal({
      message: `Non-200 status code: '${fetchRes.status}'`,
      data: body,
    });
  }

  // check for rpc error
  if (body.error) {
    throw rpcErrors.internal({
      data: body.error,
    });
  }
  // return successful result
  return body.result;
}
```

**Comment by legobeat** [comment]
@StrathCole Thank you for the report! This should be resolved in [`@metamask/eth-json-rpc-middleware@15.0.0`](https://github.com/MetaMask/eth-json-rpc-middleware/releases/tag/v15.0.0).
