### ISSUE TITLE
Remove node-fetch from production dependencies

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/eth-json-rpc-middleware#71]
The fetch middleware currently falls back to `node-fetch` if `global.fetch` is `undefined`. I want to say that dealing with that is not our problem, and we should get rid of it. I'm planning a breaking change for this package anyway.

**Comment by kumavis** [comment]
we have have it set to be omitted from the browser, right?

**Comment by kumavis** [comment]
no we don't. In pkgjson we need `"browser":{"node-fetch": false}`

**Comment by rekmarks** [comment]
I am unable to find documentation for most bundlers indicating that the `browser` field is supported in this way. Doesn't it also conflict with the way it's defined here? https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser

**Comment by rekmarks** [comment]
I did more digging, and found documentation for it.
- Browserify: https://github.com/browserify/browser-resolve
- Rollup: https://www.npmjs.com/package/@rollup/plugin-node-resolve
- Webpack: https://webpack.js.org/configuration/resolve/#resolvealiasfields
