### ISSUE TITLE
accidental globals

### ISSUE THREAD

**Issue by kumavis** [MetaMask/eth-json-rpc-middleware#9]
https://github.com/MetaMask/eth-json-rpc-middleware/blob/master/wallet.js#L132-L136

**Comment by Gudahtt** [comment]
That link pointed here on Jan 21, 2019: https://github.com/MetaMask/eth-json-rpc-middleware/blob/6033bc29a98d2af9fbcb2662a950f7d52d16b32f/wallet.js#L132-L136

This appears to have been fixed in https://github.com/MetaMask/eth-json-rpc-middleware/commit/b3f620b1e68e1c87607c59d6419653756b36a0e3
