### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by travishoglund** [MetaMask/eth-json-rpc-middleware#92]
It looks like this package is not compatible with v6+ of json-rpc-engine (they stopped including the src directory).

I found this because `const { createAsyncMiddleware } = require('json-rpc-engine')` was coming back undefined.

I had to make the following changes manually to support v6+:

eth-json-rpc-middleware/block-cache.js
const { createAsyncMiddleware } = require('json-rpc-engine/src/createAsyncMiddleware')
const { createAsyncMiddleware } = require('json-rpc-engine')

eth-json-rpc-middleware/scaffold.js
module.exports = require('json-rpc-engine/src/createScaffoldMiddleware')
module.exports = require('json-rpc-engine/dist/createScaffoldMiddleware').createScaffoldMiddleware

**Comment by mcmire** [comment]
I tried to reproduce this in RunKit but was unable to: https://runkit.com/mcmire/62697f0cb041210008b970d8. So this appears to be stale and I am closing this. Feel free to report back though if you are still seeing this and I will reopen.
